site_name: allink-core
pages:
  - Introduction: 'index.md'
  - Apps:
    - core: 'core/core.md'
    - core_apps: 'core/core_apps.md'
    - apps: 'core/apps.md'
  - Working on a client project:
    - 'Installation': 'client/install.md'
    - 'Fork app': 'client/fork_app.md'
    - 'Create new app': 'client/new_app.md'
    - 'Translations': 'client/translations.md'
    - 'Conventions': 'client/conventions.md'

extra_css:
    - custom.css

markdown_extensions:
    - admonition

theme: readthedocs